"use client";

import { useEffect, useState } from "react";
import { Brand, Footer } from "@/src/components/shared/Brand";
import { faqs, landingConfig, painItems, transformationItems } from "@/src/content/landing";
import { prices, products, type ProductKey } from "@/src/content/products";
import { offerSecondLine } from "@/src/domain/quiz/personalization";
import type { Pillar, QuizSession } from "@/src/domain/quiz/types";
import { pillarLabels } from "@/src/content/quiz";
import { track } from "@/src/lib/analytics";
import { loadSession } from "@/src/lib/storage/session";
import { buildCheckoutUrl } from "@/src/lib/validation/checkout";
import { PlanMockup } from "./PlanMockup";

export function OfferPage() {
  const [session, setSession] = useState<QuizSession>();
  const [checkoutError, setCheckoutError] = useState(false);
  const [sticky, setSticky] = useState(false);
  const [closed, setClosed] = useState(false);
  useEffect(() => {
    const stored = loadSession(); queueMicrotask(() => setSession(stored));
    track("offer_viewed", { primaryBlocker: stored.result?.primaryBlocker, hasDiagnostic: Boolean(stored.result) });
    const onScroll = () => setSticky(window.scrollY > window.innerHeight * .8); window.addEventListener("scroll", onScroll, { passive: true }); return () => window.removeEventListener("scroll", onScroll);
  }, []);
  const pillar: Pillar = session?.result?.primaryBlocker ?? "organization";
  const checkout = (product: ProductKey, ctaType: string) => {
    track(product === "completeProtocol" ? "cta_clicked" : "individual_plan_clicked", { product, ctaType, primaryBlocker: pillar });
    const url = buildCheckoutUrl(product, session?.utms ?? {});
    if (!url) { setCheckoutError(true); return; }
    track("checkout_redirected", { product, utms: session?.utms ?? {} });
    window.location.assign(url);
  };
  const completeCta = (label: string, type: string) => <button className="button primary button-large" onClick={() => checkout("completeProtocol", type)}>{label} →</button>;

  return <main className="offer-page">
    {session?.result && <div className="recommendation-strip"><span>RECOMENDAÇÃO BASEADA NA SUA ANÁLISE</span><b>Principal ponto identificado: {pillarLabels[pillar]}</b></div>}
    <header className="site-header offer-header"><Brand /><a href="#planos">Conhecer o Protocolo</a><a href="#oferta">Ver oferta</a></header>
    <section className="offer-hero section-pad">
      <div className="offer-copy"><span className="eyebrow">RECOMENDAÇÃO BASEADA NO SEU RESULTADO</span><h1>Saia do ciclo de procrastinação, desorganização e <em>recomeços.</em></h1><h2>{offerSecondLine[pillar]}</h2><p className="lead">Tenha acesso a cinco Planos de Execução que ajudam você a organizar sua rotina, voltar a agir, executar suas metas e construir disciplina sem depender de motivação todos os dias.</p><div className="analysis-connection"><span>SUA ANÁLISE MOSTROU</span><p>O problema não parece ser falta de capacidade. O que está faltando é um sistema que conecte organização, ação, direção e consistência.</p></div>{completeCta("QUERO COMEÇAR MINHA EVOLUÇÃO", "hero")}<p className="price-note">Acesso completo por apenas <b>{prices.complete}</b> · 7 dias de garantia</p></div>
      <div className="offer-visual"><PlanMockup /><div className="feature-line">{["Acesso imediato", "5 Planos", "Aplicação prática", "Pagamento único"].map((x) => <span key={x}>✓ {x}</span>)}</div></div>
    </section>
    {landingConfig.sections.problem && <section className="problem-section section-pad"><div className="section-heading"><span className="eyebrow">O PADRÃO POR TRÁS DO PROBLEMA</span><h2>Você sabe o que precisa fazer. O problema é conseguir fazer isso de forma constante.</h2><p>Durante alguns dias, parece que tudo vai mudar. Depois, a motivação diminui, a rotina volta a ficar desorganizada, tarefas são adiadas e surge novamente a sensação de precisar recomeçar do zero. Essas dificuldades fazem parte do mesmo ciclo.</p></div><div className="cycle-large">{["Desorganização", "Adiamento", "Falta de progresso", "Culpa", "Novo recomeço"].map((x, i) => <div key={x}><span>0{i + 1}</span><b>{x}</b></div>)}</div><div className="identify-grid"><h3>O Protocolo foi criado para quem:</h3>{painItems.map((item) => <div className={session?.mainPainAnswer === item.id ? "matched" : ""} key={item.id}><span>✓</span><p>{item.text}</p>{session?.mainPainAnswer === item.id && <small>VOCÊ INDICOU ESTE PONTO</small>}</div>)}</div></section>}
    <section className="solution-intro section-pad" id="planos"><span className="eyebrow">UMA METODOLOGIA, CINCO ETAPAS</span><h2>Conheça o <em>Protocolo da Evolução</em></h2><p>Metodologia prática composta por cinco Planos de Execução. Cada Plano trabalha uma etapa específica da sua mudança, em sequência lógica, para você não tentar mudar tudo ao mesmo tempo e abandonar novamente.</p></section>
    {landingConfig.sections.plans && <section className="plans-section section-pad">{products.map((product) => <article className="plan-card" key={product.key}><div className="plan-number">{product.number}</div><div><span>PLANO DE EXECUÇÃO</span><h3>{product.name}</h3><p className="plan-promise">{product.promise}</p><ul>{product.contents.map((item) => <li key={item}>{item}</li>)}</ul></div></article>)}<div className="center-cta">{completeCta("QUERO ACESSO AOS CINCO PLANOS", "plans")}</div></section>}
    {landingConfig.sections.transformation && <section className="transformation section-pad"><div className="section-heading"><span className="eyebrow">TRANSFORMAÇÃO POSSÍVEL</span><h2>O que pode mudar quando você finalmente segue um sistema completo.</h2></div><div className="transformation-grid">{transformationItems.map((item, i) => <div key={item}><span>{String(i + 1).padStart(2, "0")}</span><p>{item}</p></div>)}</div><blockquote>Você não precisa mudar tudo de uma vez. Precisa começar pela etapa certa e seguir um plano possível.</blockquote></section>}
    {landingConfig.sections.method && <section className="method-section section-pad"><div className="section-heading"><span className="eyebrow">MENOS TEORIA. MAIS MOVIMENTO.</span><h2>Não é mais um material cheio de teoria para você ler e esquecer.</h2></div><div className="movement-grid">{[["01", "Entender", "Identifique o padrão que limita seu progresso."], ["02", "Aplicar", "Execute pequenas ações imediatamente."], ["03", "Continuar", "Crie estrutura que não dependa de motivação perfeita."]].map(([n,t,p]) => <div key={t}><span>{n}</span><h3>{t}</h3><p>{p}</p></div>)}</div><div className="comparison"><div><span>CONTEÚDO COMUM</span>{["Teoria excessiva", "Dicas soltas", "Pouca aplicação", "Sem sequência clara"].map(x => <p key={x}>× {x}</p>)}</div><div className="protocol-column"><span>PROTOCOLO DA EVOLUÇÃO</span>{["5 Planos conectados", "Etapas em sequência", "Exercícios objetivos", "Sistema de continuidade"].map(x => <p key={x}>✓ {x}</p>)}</div></div></section>}
    {landingConfig.sections.pricing && <section className="pricing-section section-pad" id="oferta"><div className="pricing-copy"><span className="eyebrow">ACESSO COMPLETO</span><h2>Cinco Planos. Uma sequência. Um único investimento.</h2><p>Adquiridos separadamente, os cinco Planos custariam:</p><div className="price-list">{products.map((p) => <div key={p.key}><span>{p.name}</span><b>{prices.individual}</b></div>)}<div className="total"><span>Total separado</span><b>{prices.separateTotal}</b></div></div></div><div className="offer-card"><span className="offer-tag">PROTOCOLO COMPLETO</span><p>De <s>{prices.separateTotal}</s> por</p><strong>{prices.complete}</strong><small>pagamento único</small><ul><li>5 Planos de Execução</li><li>Acesso digital imediato</li><li>Sem mensalidade ou recorrência</li><li>7 dias de garantia</li></ul>{completeCta("QUERO O PROTOCOLO COMPLETO", "pricing")}<p>Por apenas <b>{prices.difference}</b> a mais do que um único Plano, você recebe os cinco.</p></div></section>}
    {landingConfig.sections.individual && <section className="individual-section section-pad"><div className="section-heading"><span className="eyebrow">OUTRA FORMA DE COMEÇAR</span><h2>Prefere começar por um único Plano?</h2><p>Escolha uma dificuldade específica por {prices.individual}. O Protocolo completo continua sendo a opção para trabalhar o ciclo inteiro.</p></div><div className="individual-grid">{products.map((p) => <article key={p.key}><span>{p.number}</span><h3>{p.name}</h3><p>{p.promise}</p><b>{prices.individual}</b><button className="button secondary" onClick={() => checkout(p.key, "individual_card")}>ESCOLHER ESTE PLANO</button></article>)}</div><div className="value-callout"><span>1 Plano · {prices.individual}</span><b>Por {prices.difference} a mais</b><span>5 Planos · {prices.complete}</span></div><div className="center-cta">{completeCta("QUERO O PROTOCOLO COMPLETO", "individual_compare")}</div></section>}
    {landingConfig.sections.preview && <section className="preview-section section-pad"><div className="section-heading"><span className="eyebrow">VEJA POR DENTRO ANTES DE DECIDIR</span><h2>Aplicação clara. Páginas objetivas. Sequência visível.</h2></div><div className="preview-grid"><div className="preview-sheet"><span>PLANO 01</span><h3>Mapa da rotina atual</h3><div className="fake-lines"><i/><i/><i/></div><div className="fake-checks"><i/><i/><i/></div></div><div className="preview-sheet dark"><span>EXERCÍCIO</span><h3>Ação mínima viável</h3><p>Qual menor versão desta ação você consegue executar hoje?</p><div className="write-line" /></div><div className="preview-sheet"><span>REVISÃO</span><h3>Seu progresso da semana</h3><div className="day-dots">{[1,2,3,4,5,6,7].map(n => <i key={n}>{n}</i>)}</div><div className="fake-lines"><i/><i/></div></div></div></section>}
    {landingConfig.sections.access && <section className="access-section section-pad"><div className="section-heading"><span className="eyebrow">COMO FUNCIONA O ACESSO</span><h2>Comece poucos minutos após a compra.</h2></div><div className="steps-grid">{[["01", "Finalize a compra", "Clique no botão e conclua o pagamento com segurança."], ["02", "Receba o acesso", "As instruções chegam no e-mail cadastrado."], ["03", "Comece pela base", "Inicie no Vida em Ordem e siga a sequência recomendada."]].map(([n,t,p]) => <div key={n}><span>{n}</span><h3>{t}</h3><p>{p}</p></div>)}</div><p className="device-note">Acesso pelo celular, computador ou tablet.</p><div className="center-cta">{completeCta("QUERO COMEÇAR AGORA", "access")}</div></section>}
    {landingConfig.sections.kit && <section className="kit-section section-pad"><div><span className="eyebrow">OPCIONAL NO CHECKOUT</span><h2>Quer tornar a aplicação ainda mais simples?</h2><p>Durante a finalização, você poderá adicionar o Kit de Execução: planners, checklists, rastreadores, revisões, calendários e páginas de acompanhamento.</p></div><div className="kit-note"><b>O Protocolo ensina o processo.</b><span>O Kit facilita a execução diária.</span><strong>{prices.kit}</strong><small>adicional no checkout</small></div></section>}
    {landingConfig.sections.guarantee && <section className="guarantee-section section-pad"><div className="guarantee-seal"><strong>7</strong><span>DIAS DE<br/>GARANTIA</span></div><div><span className="eyebrow">RISCO REDUZIDO</span><h2>Você tem 7 dias para conhecer o Protocolo.</h2><p>Acesse os materiais e avalie se o conteúdo faz sentido para sua realidade. Se decidir que não é adequado, poderá solicitar reembolso dentro do prazo e das condições da plataforma de pagamento.</p>{completeCta("QUERO CONHECER O PROTOCOLO SEM RISCO", "guarantee")}</div></section>}
    {landingConfig.sections.faq && <section className="faq-section section-pad"><div className="section-heading"><span className="eyebrow">DÚVIDAS FREQUENTES</span><h2>Antes de começar.</h2></div><div className="faq-list">{faqs.map(([q,a]) => <details key={q}><summary>{q}<span>+</span></summary><p>{a}</p></details>)}</div></section>}
    <section className="final-section section-pad"><span className="eyebrow">SEU PRÓXIMO PASSO</span><h2>Você pode continuar esperando o próximo recomeço ou construir uma forma diferente de continuar.</h2><p>O que talvez tenha faltado não foi vontade. Foi uma estrutura que mostrasse onde começar, o que fazer em seguida e como voltar depois de falhar. O Protocolo da Evolução foi criado para entregar essa estrutura.</p><div className="final-summary"><span>5 Planos</span><span>Acesso imediato</span><span>Pagamento único</span><span>7 dias de garantia</span></div><p className="final-price">De <s>{prices.separateTotal}</s> por <strong>{prices.complete}</strong></p>{completeCta("SIM, QUERO COMEÇAR MINHA EVOLUÇÃO", "final")}<small>Checkout seguro · acesso digital após confirmação</small></section>
    <Footer />
    {checkoutError && <div className="checkout-alert" role="alert"><button aria-label="Fechar aviso" onClick={() => setCheckoutError(false)}>×</button><b>Checkout ainda não configurado.</b><p>Adicione a URL real nas variáveis de ambiente antes de publicar a campanha.</p></div>}
    {sticky && !closed && <div className="mobile-sticky"><button aria-label="Fechar barra" onClick={() => setClosed(true)}>×</button><div><span>Protocolo completo</span><b>{prices.complete}</b></div><button className="button primary" onClick={() => checkout("completeProtocol", "mobile_sticky")}>QUERO COMEÇAR</button></div>}
  </main>;
}
